### ISSUE TITLE
Is it possible to add son-emu as platform?

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-editor-backend#4]
There is a  button to add a platform to workspace (can be used to send a service package to it?)
but an error is thrown when trying to add son-emu:

Could not reach server http://127.0.0.1:5000/api/v2/packages at url 'son_emu':HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v2/packages (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

Although the url is correct and working (son-emu dummygatekeeper has a get and post method for it).
The editor seems to connect to a url at the backend, which does not exist:

Request URL:http://localhost/backend/workspaces/2
Request Method:PUT
Status Code:404 NOT FOUND
Remote Address:127.0.0.1:80
...

**Comment by mpeuster** [comment]
Is the backend running in a container? In this case  http://127.0.0.1:5000/api/v2/packages would point to the backend container itself and not to the dummy GK, right? 

We always considered remote platforms, so we never encountered this case. A solution might be to use the IP of the docker0 interface of the host machine to access the GK?

**Comment by stevenvanrossem** [comment]
Ah yes indeed! backend is running in container, so this url points to itself!
if I try the docker0 (http://172.19.0.1:5000) error is gone, and also uploading seems to work!
